/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package FlightMgmtSystemService.model.impl;

import FlightMgmtSystemService.model.Flight;
import FlightMgmtSystemService.model.FlightModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Flight service. Represents a row in the &quot;FLIGHT_Flight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FlightModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FlightImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FlightImpl
 * @generated
 */
@JSON(strict = true)
public class FlightModelImpl
	extends BaseModelImpl<Flight> implements FlightModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a flight model instance should use the <code>Flight</code> interface instead.
	 */
	public static final String TABLE_NAME = "FLIGHT_Flight";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"flightId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"flightNumber", Types.VARCHAR}, {"airline", Types.VARCHAR},
		{"departureAirport", Types.VARCHAR}, {"arrivalAirport", Types.VARCHAR},
		{"departureTime", Types.TIMESTAMP}, {"arrivalTime", Types.TIMESTAMP},
		{"availableSeats", Types.INTEGER}, {"price", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("flightId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("flightNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("airline", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("departureAirport", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("arrivalAirport", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("departureTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("arrivalTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("availableSeats", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("price", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FLIGHT_Flight (uuid_ VARCHAR(75) null,flightId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,flightNumber VARCHAR(75) null,airline VARCHAR(75) null,departureAirport VARCHAR(75) null,arrivalAirport VARCHAR(75) null,departureTime DATE null,arrivalTime DATE null,availableSeats INTEGER,price DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table FLIGHT_Flight";

	public static final String ORDER_BY_JPQL =
		" ORDER BY flight.flightNumber ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FLIGHT_Flight.flightNumber ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FLIGHTNUMBER_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FlightModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _flightId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFlightId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _flightId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Flight.class;
	}

	@Override
	public String getModelClassName() {
		return Flight.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Flight, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Flight, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Flight, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Flight)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Flight, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Flight, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Flight)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Flight, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Flight, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Flight, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Flight, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Flight, Object>>();

			attributeGetterFunctions.put("uuid", Flight::getUuid);
			attributeGetterFunctions.put("flightId", Flight::getFlightId);
			attributeGetterFunctions.put("groupId", Flight::getGroupId);
			attributeGetterFunctions.put("companyId", Flight::getCompanyId);
			attributeGetterFunctions.put("userId", Flight::getUserId);
			attributeGetterFunctions.put("userName", Flight::getUserName);
			attributeGetterFunctions.put("createDate", Flight::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Flight::getModifiedDate);
			attributeGetterFunctions.put(
				"flightNumber", Flight::getFlightNumber);
			attributeGetterFunctions.put("airline", Flight::getAirline);
			attributeGetterFunctions.put(
				"departureAirport", Flight::getDepartureAirport);
			attributeGetterFunctions.put(
				"arrivalAirport", Flight::getArrivalAirport);
			attributeGetterFunctions.put(
				"departureTime", Flight::getDepartureTime);
			attributeGetterFunctions.put("arrivalTime", Flight::getArrivalTime);
			attributeGetterFunctions.put(
				"availableSeats", Flight::getAvailableSeats);
			attributeGetterFunctions.put("price", Flight::getPrice);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Flight, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Flight, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Flight, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Flight, String>)Flight::setUuid);
			attributeSetterBiConsumers.put(
				"flightId", (BiConsumer<Flight, Long>)Flight::setFlightId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Flight, Long>)Flight::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Flight, Long>)Flight::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Flight, Long>)Flight::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Flight, String>)Flight::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Flight, Date>)Flight::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Flight, Date>)Flight::setModifiedDate);
			attributeSetterBiConsumers.put(
				"flightNumber",
				(BiConsumer<Flight, String>)Flight::setFlightNumber);
			attributeSetterBiConsumers.put(
				"airline", (BiConsumer<Flight, String>)Flight::setAirline);
			attributeSetterBiConsumers.put(
				"departureAirport",
				(BiConsumer<Flight, String>)Flight::setDepartureAirport);
			attributeSetterBiConsumers.put(
				"arrivalAirport",
				(BiConsumer<Flight, String>)Flight::setArrivalAirport);
			attributeSetterBiConsumers.put(
				"departureTime",
				(BiConsumer<Flight, Date>)Flight::setDepartureTime);
			attributeSetterBiConsumers.put(
				"arrivalTime",
				(BiConsumer<Flight, Date>)Flight::setArrivalTime);
			attributeSetterBiConsumers.put(
				"availableSeats",
				(BiConsumer<Flight, Integer>)Flight::setAvailableSeats);
			attributeSetterBiConsumers.put(
				"price", (BiConsumer<Flight, Double>)Flight::setPrice);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFlightId() {
		return _flightId;
	}

	@Override
	public void setFlightId(long flightId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_flightId = flightId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFlightNumber() {
		if (_flightNumber == null) {
			return "";
		}
		else {
			return _flightNumber;
		}
	}

	@Override
	public void setFlightNumber(String flightNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_flightNumber = flightNumber;
	}

	@JSON
	@Override
	public String getAirline() {
		if (_airline == null) {
			return "";
		}
		else {
			return _airline;
		}
	}

	@Override
	public void setAirline(String airline) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_airline = airline;
	}

	@JSON
	@Override
	public String getDepartureAirport() {
		if (_departureAirport == null) {
			return "";
		}
		else {
			return _departureAirport;
		}
	}

	@Override
	public void setDepartureAirport(String departureAirport) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departureAirport = departureAirport;
	}

	@JSON
	@Override
	public String getArrivalAirport() {
		if (_arrivalAirport == null) {
			return "";
		}
		else {
			return _arrivalAirport;
		}
	}

	@Override
	public void setArrivalAirport(String arrivalAirport) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arrivalAirport = arrivalAirport;
	}

	@JSON
	@Override
	public Date getDepartureTime() {
		return _departureTime;
	}

	@Override
	public void setDepartureTime(Date departureTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departureTime = departureTime;
	}

	@JSON
	@Override
	public Date getArrivalTime() {
		return _arrivalTime;
	}

	@Override
	public void setArrivalTime(Date arrivalTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arrivalTime = arrivalTime;
	}

	@JSON
	@Override
	public int getAvailableSeats() {
		return _availableSeats;
	}

	@Override
	public void setAvailableSeats(int availableSeats) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_availableSeats = availableSeats;
	}

	@JSON
	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Flight.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Flight.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Flight toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Flight>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FlightImpl flightImpl = new FlightImpl();

		flightImpl.setUuid(getUuid());
		flightImpl.setFlightId(getFlightId());
		flightImpl.setGroupId(getGroupId());
		flightImpl.setCompanyId(getCompanyId());
		flightImpl.setUserId(getUserId());
		flightImpl.setUserName(getUserName());
		flightImpl.setCreateDate(getCreateDate());
		flightImpl.setModifiedDate(getModifiedDate());
		flightImpl.setFlightNumber(getFlightNumber());
		flightImpl.setAirline(getAirline());
		flightImpl.setDepartureAirport(getDepartureAirport());
		flightImpl.setArrivalAirport(getArrivalAirport());
		flightImpl.setDepartureTime(getDepartureTime());
		flightImpl.setArrivalTime(getArrivalTime());
		flightImpl.setAvailableSeats(getAvailableSeats());
		flightImpl.setPrice(getPrice());

		flightImpl.resetOriginalValues();

		return flightImpl;
	}

	@Override
	public Flight cloneWithOriginalValues() {
		FlightImpl flightImpl = new FlightImpl();

		flightImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		flightImpl.setFlightId(this.<Long>getColumnOriginalValue("flightId"));
		flightImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		flightImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		flightImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		flightImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		flightImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		flightImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		flightImpl.setFlightNumber(
			this.<String>getColumnOriginalValue("flightNumber"));
		flightImpl.setAirline(this.<String>getColumnOriginalValue("airline"));
		flightImpl.setDepartureAirport(
			this.<String>getColumnOriginalValue("departureAirport"));
		flightImpl.setArrivalAirport(
			this.<String>getColumnOriginalValue("arrivalAirport"));
		flightImpl.setDepartureTime(
			this.<Date>getColumnOriginalValue("departureTime"));
		flightImpl.setArrivalTime(
			this.<Date>getColumnOriginalValue("arrivalTime"));
		flightImpl.setAvailableSeats(
			this.<Integer>getColumnOriginalValue("availableSeats"));
		flightImpl.setPrice(this.<Double>getColumnOriginalValue("price"));

		return flightImpl;
	}

	@Override
	public int compareTo(Flight flight) {
		int value = 0;

		value = getFlightNumber().compareTo(flight.getFlightNumber());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Flight)) {
			return false;
		}

		Flight flight = (Flight)object;

		long primaryKey = flight.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Flight> toCacheModel() {
		FlightCacheModel flightCacheModel = new FlightCacheModel();

		flightCacheModel.uuid = getUuid();

		String uuid = flightCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			flightCacheModel.uuid = null;
		}

		flightCacheModel.flightId = getFlightId();

		flightCacheModel.groupId = getGroupId();

		flightCacheModel.companyId = getCompanyId();

		flightCacheModel.userId = getUserId();

		flightCacheModel.userName = getUserName();

		String userName = flightCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			flightCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			flightCacheModel.createDate = createDate.getTime();
		}
		else {
			flightCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			flightCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			flightCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		flightCacheModel.flightNumber = getFlightNumber();

		String flightNumber = flightCacheModel.flightNumber;

		if ((flightNumber != null) && (flightNumber.length() == 0)) {
			flightCacheModel.flightNumber = null;
		}

		flightCacheModel.airline = getAirline();

		String airline = flightCacheModel.airline;

		if ((airline != null) && (airline.length() == 0)) {
			flightCacheModel.airline = null;
		}

		flightCacheModel.departureAirport = getDepartureAirport();

		String departureAirport = flightCacheModel.departureAirport;

		if ((departureAirport != null) && (departureAirport.length() == 0)) {
			flightCacheModel.departureAirport = null;
		}

		flightCacheModel.arrivalAirport = getArrivalAirport();

		String arrivalAirport = flightCacheModel.arrivalAirport;

		if ((arrivalAirport != null) && (arrivalAirport.length() == 0)) {
			flightCacheModel.arrivalAirport = null;
		}

		Date departureTime = getDepartureTime();

		if (departureTime != null) {
			flightCacheModel.departureTime = departureTime.getTime();
		}
		else {
			flightCacheModel.departureTime = Long.MIN_VALUE;
		}

		Date arrivalTime = getArrivalTime();

		if (arrivalTime != null) {
			flightCacheModel.arrivalTime = arrivalTime.getTime();
		}
		else {
			flightCacheModel.arrivalTime = Long.MIN_VALUE;
		}

		flightCacheModel.availableSeats = getAvailableSeats();

		flightCacheModel.price = getPrice();

		return flightCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Flight, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Flight, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Flight, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Flight)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Flight>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Flight.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _flightId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _flightNumber;
	private String _airline;
	private String _departureAirport;
	private String _arrivalAirport;
	private Date _departureTime;
	private Date _arrivalTime;
	private int _availableSeats;
	private double _price;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Flight, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Flight)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("flightId", _flightId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("flightNumber", _flightNumber);
		_columnOriginalValues.put("airline", _airline);
		_columnOriginalValues.put("departureAirport", _departureAirport);
		_columnOriginalValues.put("arrivalAirport", _arrivalAirport);
		_columnOriginalValues.put("departureTime", _departureTime);
		_columnOriginalValues.put("arrivalTime", _arrivalTime);
		_columnOriginalValues.put("availableSeats", _availableSeats);
		_columnOriginalValues.put("price", _price);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("flightId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("flightNumber", 256L);

		columnBitmasks.put("airline", 512L);

		columnBitmasks.put("departureAirport", 1024L);

		columnBitmasks.put("arrivalAirport", 2048L);

		columnBitmasks.put("departureTime", 4096L);

		columnBitmasks.put("arrivalTime", 8192L);

		columnBitmasks.put("availableSeats", 16384L);

		columnBitmasks.put("price", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Flight _escapedModel;

}