/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.books.model.impl;

import com.ats.books.model.BookCategory;
import com.ats.books.service.BookCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the BookCategory service. Represents a row in the &quot;BOOKKK_BookCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookCategoryImpl
 * @see BookCategory
 * @generated
 */
public abstract class BookCategoryBaseImpl
	extends BookCategoryModelImpl implements BookCategory {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a book category model instance should use the <code>BookCategory</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BookCategoryLocalServiceUtil.addBookCategory(this);
		}
		else {
			BookCategoryLocalServiceUtil.updateBookCategory(this);
		}
	}

}