/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CheckInOutApp service. Represents a row in the &quot;ATS_CheckInOutApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>PracticeService1.model.impl.CheckInOutAppModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>PracticeService1.model.impl.CheckInOutAppImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CheckInOutApp
 * @generated
 */
@ProviderType
public interface CheckInOutAppModel
	extends BaseModel<CheckInOutApp>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a check in out app model instance should use the {@link CheckInOutApp} interface instead.
	 */

	/**
	 * Returns the primary key of this check in out app.
	 *
	 * @return the primary key of this check in out app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this check in out app.
	 *
	 * @param primaryKey the primary key of this check in out app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this check in out app.
	 *
	 * @return the uuid of this check in out app
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this check in out app.
	 *
	 * @param uuid the uuid of this check in out app
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the log ID of this check in out app.
	 *
	 * @return the log ID of this check in out app
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this check in out app.
	 *
	 * @param logId the log ID of this check in out app
	 */
	public void setLogId(long logId);

	/**
	 * Returns the group ID of this check in out app.
	 *
	 * @return the group ID of this check in out app
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this check in out app.
	 *
	 * @param groupId the group ID of this check in out app
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this check in out app.
	 *
	 * @return the company ID of this check in out app
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this check in out app.
	 *
	 * @param companyId the company ID of this check in out app
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this check in out app.
	 *
	 * @return the user ID of this check in out app
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this check in out app.
	 *
	 * @param userId the user ID of this check in out app
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this check in out app.
	 *
	 * @return the user uuid of this check in out app
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this check in out app.
	 *
	 * @param userUuid the user uuid of this check in out app
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this check in out app.
	 *
	 * @return the user name of this check in out app
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this check in out app.
	 *
	 * @param userName the user name of this check in out app
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this check in out app.
	 *
	 * @return the create date of this check in out app
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this check in out app.
	 *
	 * @param createDate the create date of this check in out app
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this check in out app.
	 *
	 * @return the modified date of this check in out app
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this check in out app.
	 *
	 * @param modifiedDate the modified date of this check in out app
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the check in time of this check in out app.
	 *
	 * @return the check in time of this check in out app
	 */
	public Date getCheckInTime();

	/**
	 * Sets the check in time of this check in out app.
	 *
	 * @param checkInTime the check in time of this check in out app
	 */
	public void setCheckInTime(Date checkInTime);

	/**
	 * Returns the check out time of this check in out app.
	 *
	 * @return the check out time of this check in out app
	 */
	public Date getCheckOutTime();

	/**
	 * Sets the check out time of this check in out app.
	 *
	 * @param checkOutTime the check out time of this check in out app
	 */
	public void setCheckOutTime(Date checkOutTime);

	/**
	 * Returns the remarks of this check in out app.
	 *
	 * @return the remarks of this check in out app
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this check in out app.
	 *
	 * @param remarks the remarks of this check in out app
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the location of this check in out app.
	 *
	 * @return the location of this check in out app
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this check in out app.
	 *
	 * @param location the location of this check in out app
	 */
	public void setLocation(String location);

	@Override
	public CheckInOutApp cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}