/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserProfile service. Represents a row in the &quot;ATS_UserProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>PracticeService1.model.impl.UserProfileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>PracticeService1.model.impl.UserProfileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfile
 * @generated
 */
@ProviderType
public interface UserProfileModel extends BaseModel<UserProfile> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user profile model instance should use the {@link UserProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this user profile.
	 *
	 * @return the primary key of this user profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user profile.
	 *
	 * @param primaryKey the primary key of this user profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user profile.
	 *
	 * @return the user ID of this user profile
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user profile.
	 *
	 * @param userId the user ID of this user profile
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user profile.
	 *
	 * @return the user uuid of this user profile
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user profile.
	 *
	 * @param userUuid the user uuid of this user profile
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user profile.
	 *
	 * @return the user name of this user profile
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user profile.
	 *
	 * @param userName the user name of this user profile
	 */
	public void setUserName(String userName);

	/**
	 * Returns the password of this user profile.
	 *
	 * @return the password of this user profile
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this user profile.
	 *
	 * @param password the password of this user profile
	 */
	public void setPassword(String password);

	@Override
	public UserProfile cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}