/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.service.base;

import PracticeService1.model.CheckInOutApp;

import PracticeService1.service.CheckInOutAppLocalService;
import PracticeService1.service.persistence.CheckInOutAppPersistence;
import PracticeService1.service.persistence.UserProfilePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the check in out app local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link PracticeService1.service.impl.CheckInOutAppLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PracticeService1.service.impl.CheckInOutAppLocalServiceImpl
 * @generated
 */
public abstract class CheckInOutAppLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CheckInOutAppLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CheckInOutAppLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PracticeService1.service.CheckInOutAppLocalServiceUtil</code>.
	 */

	/**
	 * Adds the check in out app to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CheckInOutAppLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checkInOutApp the check in out app
	 * @return the check in out app that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CheckInOutApp addCheckInOutApp(CheckInOutApp checkInOutApp) {
		checkInOutApp.setNew(true);

		return checkInOutAppPersistence.update(checkInOutApp);
	}

	/**
	 * Creates a new check in out app with the primary key. Does not add the check in out app to the database.
	 *
	 * @param logId the primary key for the new check in out app
	 * @return the new check in out app
	 */
	@Override
	@Transactional(enabled = false)
	public CheckInOutApp createCheckInOutApp(long logId) {
		return checkInOutAppPersistence.create(logId);
	}

	/**
	 * Deletes the check in out app with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CheckInOutAppLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param logId the primary key of the check in out app
	 * @return the check in out app that was removed
	 * @throws PortalException if a check in out app with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CheckInOutApp deleteCheckInOutApp(long logId)
		throws PortalException {

		return checkInOutAppPersistence.remove(logId);
	}

	/**
	 * Deletes the check in out app from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CheckInOutAppLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checkInOutApp the check in out app
	 * @return the check in out app that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CheckInOutApp deleteCheckInOutApp(CheckInOutApp checkInOutApp) {
		return checkInOutAppPersistence.remove(checkInOutApp);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return checkInOutAppPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CheckInOutApp.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return checkInOutAppPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>PracticeService1.model.impl.CheckInOutAppModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return checkInOutAppPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>PracticeService1.model.impl.CheckInOutAppModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return checkInOutAppPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return checkInOutAppPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return checkInOutAppPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CheckInOutApp fetchCheckInOutApp(long logId) {
		return checkInOutAppPersistence.fetchByPrimaryKey(logId);
	}

	/**
	 * Returns the check in out app matching the UUID and group.
	 *
	 * @param uuid the check in out app's UUID
	 * @param groupId the primary key of the group
	 * @return the matching check in out app, or <code>null</code> if a matching check in out app could not be found
	 */
	@Override
	public CheckInOutApp fetchCheckInOutAppByUuidAndGroupId(
		String uuid, long groupId) {

		return checkInOutAppPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the check in out app with the primary key.
	 *
	 * @param logId the primary key of the check in out app
	 * @return the check in out app
	 * @throws PortalException if a check in out app with the primary key could not be found
	 */
	@Override
	public CheckInOutApp getCheckInOutApp(long logId) throws PortalException {
		return checkInOutAppPersistence.findByPrimaryKey(logId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(checkInOutAppLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CheckInOutApp.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("logId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			checkInOutAppLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CheckInOutApp.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("logId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(checkInOutAppLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CheckInOutApp.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("logId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<CheckInOutApp>() {

				@Override
				public void performAction(CheckInOutApp checkInOutApp)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, checkInOutApp);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(CheckInOutApp.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return checkInOutAppPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CheckInOutAppLocalServiceImpl#deleteCheckInOutApp(CheckInOutApp) to avoid orphaned data");
		}

		return checkInOutAppLocalService.deleteCheckInOutApp(
			(CheckInOutApp)persistedModel);
	}

	@Override
	public BasePersistence<CheckInOutApp> getBasePersistence() {
		return checkInOutAppPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return checkInOutAppPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the check in out apps matching the UUID and company.
	 *
	 * @param uuid the UUID of the check in out apps
	 * @param companyId the primary key of the company
	 * @return the matching check in out apps, or an empty list if no matches were found
	 */
	@Override
	public List<CheckInOutApp> getCheckInOutAppsByUuidAndCompanyId(
		String uuid, long companyId) {

		return checkInOutAppPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of check in out apps matching the UUID and company.
	 *
	 * @param uuid the UUID of the check in out apps
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of check in out apps
	 * @param end the upper bound of the range of check in out apps (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching check in out apps, or an empty list if no matches were found
	 */
	@Override
	public List<CheckInOutApp> getCheckInOutAppsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<CheckInOutApp> orderByComparator) {

		return checkInOutAppPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the check in out app matching the UUID and group.
	 *
	 * @param uuid the check in out app's UUID
	 * @param groupId the primary key of the group
	 * @return the matching check in out app
	 * @throws PortalException if a matching check in out app could not be found
	 */
	@Override
	public CheckInOutApp getCheckInOutAppByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return checkInOutAppPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the check in out apps.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>PracticeService1.model.impl.CheckInOutAppModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of check in out apps
	 * @param end the upper bound of the range of check in out apps (not inclusive)
	 * @return the range of check in out apps
	 */
	@Override
	public List<CheckInOutApp> getCheckInOutApps(int start, int end) {
		return checkInOutAppPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of check in out apps.
	 *
	 * @return the number of check in out apps
	 */
	@Override
	public int getCheckInOutAppsCount() {
		return checkInOutAppPersistence.countAll();
	}

	/**
	 * Updates the check in out app in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CheckInOutAppLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checkInOutApp the check in out app
	 * @return the check in out app that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CheckInOutApp updateCheckInOutApp(CheckInOutApp checkInOutApp) {
		return checkInOutAppPersistence.update(checkInOutApp);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CheckInOutAppLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		checkInOutAppLocalService = (CheckInOutAppLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CheckInOutAppLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CheckInOutApp.class;
	}

	protected String getModelClassName() {
		return CheckInOutApp.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = checkInOutAppPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CheckInOutAppLocalService checkInOutAppLocalService;

	@Reference
	protected CheckInOutAppPersistence checkInOutAppPersistence;

	@Reference
	protected UserProfilePersistence userProfilePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CheckInOutAppLocalServiceBaseImpl.class);

}