/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.books.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Author service. Represents a row in the &quot;BOOKKK_Author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ats.books.model.impl.AuthorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ats.books.model.impl.AuthorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Author
 * @generated
 */
@ProviderType
public interface AuthorModel extends BaseModel<Author> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link Author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorId the author ID of this author
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the liferay user ID of this author.
	 *
	 * @return the liferay user ID of this author
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this author.
	 *
	 * @param liferayUserId the liferay user ID of this author
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this author.
	 *
	 * @return the liferay user uuid of this author
	 */
	public String getLiferayUserUuid();

	/**
	 * Sets the liferay user uuid of this author.
	 *
	 * @param liferayUserUuid the liferay user uuid of this author
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	@Override
	public Author cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}