/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.books.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BookCategory service. Represents a row in the &quot;BOOKKK_BookCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ats.books.model.impl.BookCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ats.books.model.impl.BookCategoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookCategory
 * @generated
 */
@ProviderType
public interface BookCategoryModel
	extends BaseModel<BookCategory>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book category model instance should use the {@link BookCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this book category.
	 *
	 * @return the primary key of this book category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book category.
	 *
	 * @param primaryKey the primary key of this book category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this book category.
	 *
	 * @return the uuid of this book category
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this book category.
	 *
	 * @param uuid the uuid of this book category
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the category ID of this book category.
	 *
	 * @return the category ID of this book category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this book category.
	 *
	 * @param categoryId the category ID of this book category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this book category.
	 *
	 * @return the group ID of this book category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this book category.
	 *
	 * @param groupId the group ID of this book category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this book category.
	 *
	 * @return the company ID of this book category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this book category.
	 *
	 * @param companyId the company ID of this book category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this book category.
	 *
	 * @return the user ID of this book category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this book category.
	 *
	 * @param userId the user ID of this book category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this book category.
	 *
	 * @return the user uuid of this book category
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this book category.
	 *
	 * @param userUuid the user uuid of this book category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this book category.
	 *
	 * @return the user name of this book category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this book category.
	 *
	 * @param userName the user name of this book category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this book category.
	 *
	 * @return the create date of this book category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this book category.
	 *
	 * @param createDate the create date of this book category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book category.
	 *
	 * @return the modified date of this book category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book category.
	 *
	 * @param modifiedDate the modified date of this book category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category name of this book category.
	 *
	 * @return the category name of this book category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this book category.
	 *
	 * @param categoryName the category name of this book category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the book ID of this book category.
	 *
	 * @return the book ID of this book category
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book category.
	 *
	 * @param bookId the book ID of this book category
	 */
	public void setBookId(long bookId);

	@Override
	public BookCategory cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}