/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import fironlineser.model.PoliceStation;
import fironlineser.model.PoliceStationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PoliceStation service. Represents a row in the &quot;FIRFOO_PoliceStation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PoliceStationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PoliceStationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PoliceStationImpl
 * @generated
 */
public class PoliceStationModelImpl
	extends BaseModelImpl<PoliceStation> implements PoliceStationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a police station model instance should use the <code>PoliceStation</code> interface instead.
	 */
	public static final String TABLE_NAME = "FIRFOO_PoliceStation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"stationId", Types.BIGINT},
		{"stationName", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"jurisdictionArea", Types.VARCHAR}, {"officerInCharge", Types.VARCHAR},
		{"contactNumber", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("stationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jurisdictionArea", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("officerInCharge", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FIRFOO_PoliceStation (uuid_ VARCHAR(75) null,stationId LONG not null primary key,stationName VARCHAR(75) null,address VARCHAR(75) null,jurisdictionArea VARCHAR(75) null,officerInCharge VARCHAR(75) null,contactNumber VARCHAR(75) null,email VARCHAR(75) null,status VARCHAR(75) null,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table FIRFOO_PoliceStation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY policeStation.stationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FIRFOO_PoliceStation.stationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long JURISDICTIONAREA_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATIONNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PoliceStationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PoliceStation.class;
	}

	@Override
	public String getModelClassName() {
		return PoliceStation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PoliceStation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PoliceStation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PoliceStation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PoliceStation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PoliceStation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PoliceStation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PoliceStation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PoliceStation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PoliceStation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PoliceStation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PoliceStation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PoliceStation, Object>>();

			attributeGetterFunctions.put("uuid", PoliceStation::getUuid);
			attributeGetterFunctions.put(
				"stationId", PoliceStation::getStationId);
			attributeGetterFunctions.put(
				"stationName", PoliceStation::getStationName);
			attributeGetterFunctions.put("address", PoliceStation::getAddress);
			attributeGetterFunctions.put(
				"jurisdictionArea", PoliceStation::getJurisdictionArea);
			attributeGetterFunctions.put(
				"officerInCharge", PoliceStation::getOfficerInCharge);
			attributeGetterFunctions.put(
				"contactNumber", PoliceStation::getContactNumber);
			attributeGetterFunctions.put("email", PoliceStation::getEmail);
			attributeGetterFunctions.put("status", PoliceStation::getStatus);
			attributeGetterFunctions.put("userId", PoliceStation::getUserId);
			attributeGetterFunctions.put(
				"userName", PoliceStation::getUserName);
			attributeGetterFunctions.put(
				"createDate", PoliceStation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PoliceStation::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PoliceStation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PoliceStation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<PoliceStation, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<PoliceStation, String>)PoliceStation::setUuid);
			attributeSetterBiConsumers.put(
				"stationId",
				(BiConsumer<PoliceStation, Long>)PoliceStation::setStationId);
			attributeSetterBiConsumers.put(
				"stationName",
				(BiConsumer<PoliceStation, String>)
					PoliceStation::setStationName);
			attributeSetterBiConsumers.put(
				"address",
				(BiConsumer<PoliceStation, String>)PoliceStation::setAddress);
			attributeSetterBiConsumers.put(
				"jurisdictionArea",
				(BiConsumer<PoliceStation, String>)
					PoliceStation::setJurisdictionArea);
			attributeSetterBiConsumers.put(
				"officerInCharge",
				(BiConsumer<PoliceStation, String>)
					PoliceStation::setOfficerInCharge);
			attributeSetterBiConsumers.put(
				"contactNumber",
				(BiConsumer<PoliceStation, String>)
					PoliceStation::setContactNumber);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<PoliceStation, String>)PoliceStation::setEmail);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<PoliceStation, String>)PoliceStation::setStatus);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<PoliceStation, Long>)PoliceStation::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<PoliceStation, String>)PoliceStation::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PoliceStation, Date>)PoliceStation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PoliceStation, Date>)
					PoliceStation::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getStationId() {
		return _stationId;
	}

	@Override
	public void setStationId(long stationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stationId = stationId;
	}

	@Override
	public String getStationName() {
		if (_stationName == null) {
			return "";
		}
		else {
			return _stationName;
		}
	}

	@Override
	public void setStationName(String stationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stationName = stationName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStationName() {
		return getColumnOriginalValue("stationName");
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@Override
	public String getJurisdictionArea() {
		if (_jurisdictionArea == null) {
			return "";
		}
		else {
			return _jurisdictionArea;
		}
	}

	@Override
	public void setJurisdictionArea(String jurisdictionArea) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jurisdictionArea = jurisdictionArea;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalJurisdictionArea() {
		return getColumnOriginalValue("jurisdictionArea");
	}

	@Override
	public String getOfficerInCharge() {
		if (_officerInCharge == null) {
			return "";
		}
		else {
			return _officerInCharge;
		}
	}

	@Override
	public void setOfficerInCharge(String officerInCharge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_officerInCharge = officerInCharge;
	}

	@Override
	public String getContactNumber() {
		if (_contactNumber == null) {
			return "";
		}
		else {
			return _contactNumber;
		}
	}

	@Override
	public void setContactNumber(String contactNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactNumber = contactNumber;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PoliceStation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PoliceStation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PoliceStation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PoliceStationImpl policeStationImpl = new PoliceStationImpl();

		policeStationImpl.setUuid(getUuid());
		policeStationImpl.setStationId(getStationId());
		policeStationImpl.setStationName(getStationName());
		policeStationImpl.setAddress(getAddress());
		policeStationImpl.setJurisdictionArea(getJurisdictionArea());
		policeStationImpl.setOfficerInCharge(getOfficerInCharge());
		policeStationImpl.setContactNumber(getContactNumber());
		policeStationImpl.setEmail(getEmail());
		policeStationImpl.setStatus(getStatus());
		policeStationImpl.setUserId(getUserId());
		policeStationImpl.setUserName(getUserName());
		policeStationImpl.setCreateDate(getCreateDate());
		policeStationImpl.setModifiedDate(getModifiedDate());

		policeStationImpl.resetOriginalValues();

		return policeStationImpl;
	}

	@Override
	public PoliceStation cloneWithOriginalValues() {
		PoliceStationImpl policeStationImpl = new PoliceStationImpl();

		policeStationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		policeStationImpl.setStationId(
			this.<Long>getColumnOriginalValue("stationId"));
		policeStationImpl.setStationName(
			this.<String>getColumnOriginalValue("stationName"));
		policeStationImpl.setAddress(
			this.<String>getColumnOriginalValue("address"));
		policeStationImpl.setJurisdictionArea(
			this.<String>getColumnOriginalValue("jurisdictionArea"));
		policeStationImpl.setOfficerInCharge(
			this.<String>getColumnOriginalValue("officerInCharge"));
		policeStationImpl.setContactNumber(
			this.<String>getColumnOriginalValue("contactNumber"));
		policeStationImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		policeStationImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		policeStationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		policeStationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		policeStationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		policeStationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return policeStationImpl;
	}

	@Override
	public int compareTo(PoliceStation policeStation) {
		long primaryKey = policeStation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PoliceStation)) {
			return false;
		}

		PoliceStation policeStation = (PoliceStation)object;

		long primaryKey = policeStation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PoliceStation> toCacheModel() {
		PoliceStationCacheModel policeStationCacheModel =
			new PoliceStationCacheModel();

		policeStationCacheModel.uuid = getUuid();

		String uuid = policeStationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			policeStationCacheModel.uuid = null;
		}

		policeStationCacheModel.stationId = getStationId();

		policeStationCacheModel.stationName = getStationName();

		String stationName = policeStationCacheModel.stationName;

		if ((stationName != null) && (stationName.length() == 0)) {
			policeStationCacheModel.stationName = null;
		}

		policeStationCacheModel.address = getAddress();

		String address = policeStationCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			policeStationCacheModel.address = null;
		}

		policeStationCacheModel.jurisdictionArea = getJurisdictionArea();

		String jurisdictionArea = policeStationCacheModel.jurisdictionArea;

		if ((jurisdictionArea != null) && (jurisdictionArea.length() == 0)) {
			policeStationCacheModel.jurisdictionArea = null;
		}

		policeStationCacheModel.officerInCharge = getOfficerInCharge();

		String officerInCharge = policeStationCacheModel.officerInCharge;

		if ((officerInCharge != null) && (officerInCharge.length() == 0)) {
			policeStationCacheModel.officerInCharge = null;
		}

		policeStationCacheModel.contactNumber = getContactNumber();

		String contactNumber = policeStationCacheModel.contactNumber;

		if ((contactNumber != null) && (contactNumber.length() == 0)) {
			policeStationCacheModel.contactNumber = null;
		}

		policeStationCacheModel.email = getEmail();

		String email = policeStationCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			policeStationCacheModel.email = null;
		}

		policeStationCacheModel.status = getStatus();

		String status = policeStationCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			policeStationCacheModel.status = null;
		}

		policeStationCacheModel.userId = getUserId();

		policeStationCacheModel.userName = getUserName();

		String userName = policeStationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			policeStationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			policeStationCacheModel.createDate = createDate.getTime();
		}
		else {
			policeStationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			policeStationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			policeStationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return policeStationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PoliceStation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PoliceStation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PoliceStation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PoliceStation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PoliceStation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PoliceStation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _stationId;
	private String _stationName;
	private String _address;
	private String _jurisdictionArea;
	private String _officerInCharge;
	private String _contactNumber;
	private String _email;
	private String _status;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PoliceStation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PoliceStation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("stationId", _stationId);
		_columnOriginalValues.put("stationName", _stationName);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("jurisdictionArea", _jurisdictionArea);
		_columnOriginalValues.put("officerInCharge", _officerInCharge);
		_columnOriginalValues.put("contactNumber", _contactNumber);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("stationId", 2L);

		columnBitmasks.put("stationName", 4L);

		columnBitmasks.put("address", 8L);

		columnBitmasks.put("jurisdictionArea", 16L);

		columnBitmasks.put("officerInCharge", 32L);

		columnBitmasks.put("contactNumber", 64L);

		columnBitmasks.put("email", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("userName", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PoliceStation _escapedModel;

}