/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model.impl;

import fironlineser.model.PoliceStation;

import fironlineser.service.PoliceStationLocalServiceUtil;

/**
 * The extended model base implementation for the PoliceStation service. Represents a row in the &quot;FIRFOO_PoliceStation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PoliceStationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PoliceStationImpl
 * @see PoliceStation
 * @generated
 */
public abstract class PoliceStationBaseImpl
	extends PoliceStationModelImpl implements PoliceStation {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a police station model instance should use the <code>PoliceStation</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PoliceStationLocalServiceUtil.addPoliceStation(this);
		}
		else {
			PoliceStationLocalServiceUtil.updatePoliceStation(this);
		}
	}

}