/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PoliceStation service. Represents a row in the &quot;FIRFOO_PoliceStation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fironlineser.model.impl.PoliceStationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fironlineser.model.impl.PoliceStationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PoliceStation
 * @generated
 */
@ProviderType
public interface PoliceStationModel extends BaseModel<PoliceStation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a police station model instance should use the {@link PoliceStation} interface instead.
	 */

	/**
	 * Returns the primary key of this police station.
	 *
	 * @return the primary key of this police station
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this police station.
	 *
	 * @param primaryKey the primary key of this police station
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this police station.
	 *
	 * @return the uuid of this police station
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this police station.
	 *
	 * @param uuid the uuid of this police station
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the station ID of this police station.
	 *
	 * @return the station ID of this police station
	 */
	public long getStationId();

	/**
	 * Sets the station ID of this police station.
	 *
	 * @param stationId the station ID of this police station
	 */
	public void setStationId(long stationId);

	/**
	 * Returns the station name of this police station.
	 *
	 * @return the station name of this police station
	 */
	@AutoEscape
	public String getStationName();

	/**
	 * Sets the station name of this police station.
	 *
	 * @param stationName the station name of this police station
	 */
	public void setStationName(String stationName);

	/**
	 * Returns the address of this police station.
	 *
	 * @return the address of this police station
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this police station.
	 *
	 * @param address the address of this police station
	 */
	public void setAddress(String address);

	/**
	 * Returns the jurisdiction area of this police station.
	 *
	 * @return the jurisdiction area of this police station
	 */
	@AutoEscape
	public String getJurisdictionArea();

	/**
	 * Sets the jurisdiction area of this police station.
	 *
	 * @param jurisdictionArea the jurisdiction area of this police station
	 */
	public void setJurisdictionArea(String jurisdictionArea);

	/**
	 * Returns the officer in charge of this police station.
	 *
	 * @return the officer in charge of this police station
	 */
	@AutoEscape
	public String getOfficerInCharge();

	/**
	 * Sets the officer in charge of this police station.
	 *
	 * @param officerInCharge the officer in charge of this police station
	 */
	public void setOfficerInCharge(String officerInCharge);

	/**
	 * Returns the contact number of this police station.
	 *
	 * @return the contact number of this police station
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this police station.
	 *
	 * @param contactNumber the contact number of this police station
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the email of this police station.
	 *
	 * @return the email of this police station
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this police station.
	 *
	 * @param email the email of this police station
	 */
	public void setEmail(String email);

	/**
	 * Returns the status of this police station.
	 *
	 * @return the status of this police station
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this police station.
	 *
	 * @param status the status of this police station
	 */
	public void setStatus(String status);

	/**
	 * Returns the user ID of this police station.
	 *
	 * @return the user ID of this police station
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this police station.
	 *
	 * @param userId the user ID of this police station
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this police station.
	 *
	 * @return the user uuid of this police station
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this police station.
	 *
	 * @param userUuid the user uuid of this police station
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this police station.
	 *
	 * @return the user name of this police station
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this police station.
	 *
	 * @param userName the user name of this police station
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this police station.
	 *
	 * @return the create date of this police station
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this police station.
	 *
	 * @param createDate the create date of this police station
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this police station.
	 *
	 * @return the modified date of this police station
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this police station.
	 *
	 * @param modifiedDate the modified date of this police station
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public PoliceStation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}