##
## Check GETTING_STARTED.markdown for additional properties and their default
## values.
##

liferay.workspace.bundle.dist.include.metadata = true
liferay.workspace.modules.dir = modules
liferay.workspace.themes.dir = themes
liferay.workspace.wars.dir = modules
microsoft.translator.subscription.key = 
liferay.workspace.product = portal-7.4-ga132
target.platform.index.sources = false
## i added this below by huma byme
org.gradle.jvmargs=--add-opens java.base/java.lang=ALL-UNNAMED





#if u want to autodeploy instead of manual copy pasting the jar files in tomcat server
liferay.workspace.home.dir=D:/liferay/liferay-portal-tomcat-7.4.3.120-ga120-1718225443/liferay-portal