/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.model.impl;

import PracticeService1.model.CheckInOutApp;

import PracticeService1.service.CheckInOutAppLocalServiceUtil;

/**
 * The extended model base implementation for the CheckInOutApp service. Represents a row in the &quot;ATS_CheckInOutApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CheckInOutAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CheckInOutAppImpl
 * @see CheckInOutApp
 * @generated
 */
public abstract class CheckInOutAppBaseImpl
	extends CheckInOutAppModelImpl implements CheckInOutApp {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a check in out app model instance should use the <code>CheckInOutApp</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CheckInOutAppLocalServiceUtil.addCheckInOutApp(this);
		}
		else {
			CheckInOutAppLocalServiceUtil.updateCheckInOutApp(this);
		}
	}

}