/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.model.impl;

import PracticeService1.model.CheckInOutApp;
import PracticeService1.model.CheckInOutAppModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CheckInOutApp service. Represents a row in the &quot;ATS_CheckInOutApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CheckInOutAppModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CheckInOutAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CheckInOutAppImpl
 * @generated
 */
public class CheckInOutAppModelImpl
	extends BaseModelImpl<CheckInOutApp> implements CheckInOutAppModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a check in out app model instance should use the <code>CheckInOutApp</code> interface instead.
	 */
	public static final String TABLE_NAME = "ATS_CheckInOutApp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"logId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"checkInTime", Types.TIMESTAMP}, {"checkOutTime", Types.TIMESTAMP},
		{"remarks", Types.VARCHAR}, {"location", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkInTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkOutTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("location", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ATS_CheckInOutApp (uuid_ VARCHAR(75) null,logId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,checkInTime DATE null,checkOutTime DATE null,remarks VARCHAR(75) null,location VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ATS_CheckInOutApp";

	public static final String ORDER_BY_JPQL =
		" ORDER BY checkInOutApp.checkInTime DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ATS_CheckInOutApp.checkInTime DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHECKINTIME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CheckInOutAppModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CheckInOutApp.class;
	}

	@Override
	public String getModelClassName() {
		return CheckInOutApp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CheckInOutApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CheckInOutApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CheckInOutApp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CheckInOutApp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CheckInOutApp, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CheckInOutApp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CheckInOutApp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CheckInOutApp, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CheckInOutApp, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CheckInOutApp, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CheckInOutApp, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CheckInOutApp, Object>>();

			attributeGetterFunctions.put("uuid", CheckInOutApp::getUuid);
			attributeGetterFunctions.put("logId", CheckInOutApp::getLogId);
			attributeGetterFunctions.put("groupId", CheckInOutApp::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CheckInOutApp::getCompanyId);
			attributeGetterFunctions.put("userId", CheckInOutApp::getUserId);
			attributeGetterFunctions.put(
				"userName", CheckInOutApp::getUserName);
			attributeGetterFunctions.put(
				"createDate", CheckInOutApp::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CheckInOutApp::getModifiedDate);
			attributeGetterFunctions.put(
				"checkInTime", CheckInOutApp::getCheckInTime);
			attributeGetterFunctions.put(
				"checkOutTime", CheckInOutApp::getCheckOutTime);
			attributeGetterFunctions.put("remarks", CheckInOutApp::getRemarks);
			attributeGetterFunctions.put(
				"location", CheckInOutApp::getLocation);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CheckInOutApp, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CheckInOutApp, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<CheckInOutApp, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CheckInOutApp, String>)CheckInOutApp::setUuid);
			attributeSetterBiConsumers.put(
				"logId",
				(BiConsumer<CheckInOutApp, Long>)CheckInOutApp::setLogId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CheckInOutApp, Long>)CheckInOutApp::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CheckInOutApp, Long>)CheckInOutApp::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CheckInOutApp, Long>)CheckInOutApp::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CheckInOutApp, String>)CheckInOutApp::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CheckInOutApp, Date>)CheckInOutApp::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CheckInOutApp, Date>)
					CheckInOutApp::setModifiedDate);
			attributeSetterBiConsumers.put(
				"checkInTime",
				(BiConsumer<CheckInOutApp, Date>)CheckInOutApp::setCheckInTime);
			attributeSetterBiConsumers.put(
				"checkOutTime",
				(BiConsumer<CheckInOutApp, Date>)
					CheckInOutApp::setCheckOutTime);
			attributeSetterBiConsumers.put(
				"remarks",
				(BiConsumer<CheckInOutApp, String>)CheckInOutApp::setRemarks);
			attributeSetterBiConsumers.put(
				"location",
				(BiConsumer<CheckInOutApp, String>)CheckInOutApp::setLocation);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getLogId() {
		return _logId;
	}

	@Override
	public void setLogId(long logId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logId = logId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getCheckInTime() {
		return _checkInTime;
	}

	@Override
	public void setCheckInTime(Date checkInTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkInTime = checkInTime;
	}

	@Override
	public Date getCheckOutTime() {
		return _checkOutTime;
	}

	@Override
	public void setCheckOutTime(Date checkOutTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkOutTime = checkOutTime;
	}

	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remarks = remarks;
	}

	@Override
	public String getLocation() {
		if (_location == null) {
			return "";
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_location = location;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CheckInOutApp.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CheckInOutApp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CheckInOutApp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CheckInOutApp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CheckInOutAppImpl checkInOutAppImpl = new CheckInOutAppImpl();

		checkInOutAppImpl.setUuid(getUuid());
		checkInOutAppImpl.setLogId(getLogId());
		checkInOutAppImpl.setGroupId(getGroupId());
		checkInOutAppImpl.setCompanyId(getCompanyId());
		checkInOutAppImpl.setUserId(getUserId());
		checkInOutAppImpl.setUserName(getUserName());
		checkInOutAppImpl.setCreateDate(getCreateDate());
		checkInOutAppImpl.setModifiedDate(getModifiedDate());
		checkInOutAppImpl.setCheckInTime(getCheckInTime());
		checkInOutAppImpl.setCheckOutTime(getCheckOutTime());
		checkInOutAppImpl.setRemarks(getRemarks());
		checkInOutAppImpl.setLocation(getLocation());

		checkInOutAppImpl.resetOriginalValues();

		return checkInOutAppImpl;
	}

	@Override
	public CheckInOutApp cloneWithOriginalValues() {
		CheckInOutAppImpl checkInOutAppImpl = new CheckInOutAppImpl();

		checkInOutAppImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		checkInOutAppImpl.setLogId(this.<Long>getColumnOriginalValue("logId"));
		checkInOutAppImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		checkInOutAppImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		checkInOutAppImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		checkInOutAppImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		checkInOutAppImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		checkInOutAppImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		checkInOutAppImpl.setCheckInTime(
			this.<Date>getColumnOriginalValue("checkInTime"));
		checkInOutAppImpl.setCheckOutTime(
			this.<Date>getColumnOriginalValue("checkOutTime"));
		checkInOutAppImpl.setRemarks(
			this.<String>getColumnOriginalValue("remarks"));
		checkInOutAppImpl.setLocation(
			this.<String>getColumnOriginalValue("location"));

		return checkInOutAppImpl;
	}

	@Override
	public int compareTo(CheckInOutApp checkInOutApp) {
		int value = 0;

		value = DateUtil.compareTo(
			getCheckInTime(), checkInOutApp.getCheckInTime());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CheckInOutApp)) {
			return false;
		}

		CheckInOutApp checkInOutApp = (CheckInOutApp)object;

		long primaryKey = checkInOutApp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CheckInOutApp> toCacheModel() {
		CheckInOutAppCacheModel checkInOutAppCacheModel =
			new CheckInOutAppCacheModel();

		checkInOutAppCacheModel.uuid = getUuid();

		String uuid = checkInOutAppCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			checkInOutAppCacheModel.uuid = null;
		}

		checkInOutAppCacheModel.logId = getLogId();

		checkInOutAppCacheModel.groupId = getGroupId();

		checkInOutAppCacheModel.companyId = getCompanyId();

		checkInOutAppCacheModel.userId = getUserId();

		checkInOutAppCacheModel.userName = getUserName();

		String userName = checkInOutAppCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			checkInOutAppCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			checkInOutAppCacheModel.createDate = createDate.getTime();
		}
		else {
			checkInOutAppCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			checkInOutAppCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			checkInOutAppCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date checkInTime = getCheckInTime();

		if (checkInTime != null) {
			checkInOutAppCacheModel.checkInTime = checkInTime.getTime();
		}
		else {
			checkInOutAppCacheModel.checkInTime = Long.MIN_VALUE;
		}

		Date checkOutTime = getCheckOutTime();

		if (checkOutTime != null) {
			checkInOutAppCacheModel.checkOutTime = checkOutTime.getTime();
		}
		else {
			checkInOutAppCacheModel.checkOutTime = Long.MIN_VALUE;
		}

		checkInOutAppCacheModel.remarks = getRemarks();

		String remarks = checkInOutAppCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			checkInOutAppCacheModel.remarks = null;
		}

		checkInOutAppCacheModel.location = getLocation();

		String location = checkInOutAppCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			checkInOutAppCacheModel.location = null;
		}

		return checkInOutAppCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CheckInOutApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CheckInOutApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CheckInOutApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CheckInOutApp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CheckInOutApp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CheckInOutApp.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _logId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _checkInTime;
	private Date _checkOutTime;
	private String _remarks;
	private String _location;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CheckInOutApp, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CheckInOutApp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("logId", _logId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("checkInTime", _checkInTime);
		_columnOriginalValues.put("checkOutTime", _checkOutTime);
		_columnOriginalValues.put("remarks", _remarks);
		_columnOriginalValues.put("location", _location);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("logId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("checkInTime", 256L);

		columnBitmasks.put("checkOutTime", 512L);

		columnBitmasks.put("remarks", 1024L);

		columnBitmasks.put("location", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CheckInOutApp _escapedModel;

}