/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package PracticeService1.model.impl;

import PracticeService1.model.UserProfile;

import PracticeService1.service.UserProfileLocalServiceUtil;

/**
 * The extended model base implementation for the UserProfile service. Represents a row in the &quot;ATS_UserProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfileImpl
 * @see UserProfile
 * @generated
 */
public abstract class UserProfileBaseImpl
	extends UserProfileModelImpl implements UserProfile {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user profile model instance should use the <code>UserProfile</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserProfileLocalServiceUtil.addUserProfile(this);
		}
		else {
			UserProfileLocalServiceUtil.updateUserProfile(this);
		}
	}

}